- name: Setup Processing
  uses: ifP1/setup-processing@v1.0.2
  with:
    # Version of Processing, e.g. 3.5.4
    version: # default is 3.5.4
    # e.g. 'windows64.zip', 'windows32.zip', 'linux64.tgz'
    platform-filetype: # optional, default is linux64.tgz
