# This is a basic workflow to help you get started with Actions

name: Export Application

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  export:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Downloading Processing
      #Invoke-WebRequest -Uri https://github.com/actions/runner/releases/download/v2.169.1/actions-runner-win-x64-2.169.1.zip -OutFile actions-runner-win-x64-2.169.1.zip
      run: Invoke-WebRequest -Uri https://download.processing.org/processing-3.5.4-windows64.zip -OutFile processing.zip
      
    - name: Extracting Processing
      #Add-Type -AssemblyName System.IO.Compression.FileSystem ; [System.IO.Compression.ZipFile]::ExtractToDirectory("$PWD/actions-runner-win-x64-2.169.1.zip", "$PWD")
      run: Add-Type -AssemblyName System.IO.Compression.FileSystem ; [System.IO.Compression.ZipFile]::ExtractToDirectory("$PWD/processing.zip", "$PWD")
      
    - name: Listing the directory
      run: dir
    
    - name: Creating Libraries Folder 
      run: cd processing-3.5.4; mkdir libraries
    
    - name: Downloading Box2D
      #http://www.shiffman.net/p5/libraries/box2d_processing/box2d_processing.zip
      run: cd processing-3.5.4/libraries; Invoke-WebRequest -Uri http://www.shiffman.net/p5/libraries/box2d_processing/box2d_processing.zip -OutFile box2d_processing.zip
      
    - name: Extracting Box2D
      run: cd processing-3.5.4/libraries; Add-Type -AssemblyName System.IO.Compression.FileSystem ; [System.IO.Compression.ZipFile]::ExtractToDirectory("$PWD/box2d_processing.zip", "$PWD")
    
    - name: Executing processing-java
      run: ./processing-3.5.4/processing-java.exe --sketch="D:\a\Mocka\Mocka\Mocka" --export
    
    - name: Listing the directory - Mocka
      run: cd Mocka; dir
